--------------------------------------------------------
--  파일이 생성됨 - 월요일-8월-06-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AIRPORTTB
--------------------------------------------------------

  CREATE TABLE "SCOTT"."AIRPORTTB" 
   (	"PORT_CONTINENT" VARCHAR2(20 BYTE), 
	"PORT_COUNTRY" VARCHAR2(40 BYTE), 
	"PORT_CODE" VARCHAR2(5 BYTE), 
	"PORT_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.AIRPORTTB
SET DEFINE OFF;
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('asia','South Korea','ICN','인천공항');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('asia','South Korea','GMP','김포공항');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('america','미국','LAX','로스앤젤레스인터내셔널');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('america','미국','JFK','뉴욕존에프케네디');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('america','미국','GUM','괌');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('america','브라질','GIG','리오데자네이로인터네셔널');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('america','브라질','DFW','댈러스포트워스인터네셔널');
Insert into SCOTT.AIRPORTTB (PORT_CONTINENT,PORT_COUNTRY,PORT_CODE,PORT_NAME) values ('america','브라질','FOR','포르탈레자');
--------------------------------------------------------
--  DDL for Index SYS_C007013
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007013" ON "SCOTT"."AIRPORTTB" ("PORT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AIRPORTTB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."AIRPORTTB" ADD PRIMARY KEY ("PORT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."AIRPORTTB" MODIFY ("PORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."AIRPORTTB" MODIFY ("PORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."AIRPORTTB" MODIFY ("PORT_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."AIRPORTTB" MODIFY ("PORT_CONTINENT" NOT NULL ENABLE);

commit